from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List
import uuid

from app.db.session import get_db
from sgpi_capirestc.crud.crud_usuario import usuario
from sgpi_capirestc.schemas.domain_schemas import UsuarioBase, UsuarioUpdate, UsuarioResponse
from app.core.security import get_current_user, require_admin
from app.core.audit import log_audit_event

router = APIRouter()

@router.get("/", response_model=List[UsuarioResponse], dependencies=[Depends(require_admin)])
async def list_usuarios(skip: int = 0, limit: int = 100, db: AsyncSession = Depends(get_db)):
    return await usuario.get_multi(db, skip=skip, limit=limit)

from sgpi_capirestc.schemas.domain_schemas import UsuarioCreate

@router.post("/", response_model=UsuarioResponse, dependencies=[Depends(require_admin)])
async def create_usuario(obj_in: UsuarioCreate, db: AsyncSession = Depends(get_db), current_user: dict = Depends(get_current_user)):
    # UUID will be auto-generated by DB or Supabase in a real flow, but for now we rely on the DB default gen_random_uuid
    new_u = await usuario.create(db, obj_in=obj_in)
    
    await log_audit_event(
        db=db,
        tipo_evento="USER_CREATED",
        entidad_afectada="usuario",
        pk_entidad=str(new_u.id_usuario),
        valor_anterior=None,
        valor_nuevo=obj_in.model_dump(mode='json'),
        id_usuario=current_user.get("sub"),
    )
    return new_u

@router.get("/{id_usuario}", response_model=UsuarioResponse)
async def get_usuario(id_usuario: str, db: AsyncSession = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        user_uuid = uuid.UUID(id_usuario)
    except ValueError:
        raise HTTPException(status_code=400, detail="UUID inválido")

    u = await usuario.get_by_id(db, id_usuario=user_uuid)
    if not u:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")
        
    # Only admin or the user themselves can view their profile
    rol = current_user.get("app_metadata", {}).get("rol_sistema")
    if rol != "Administrador" and current_user.get("sub") != str(user_uuid):
        raise HTTPException(status_code=403, detail="No tiene permisos para ver otro perfil")

    return u

@router.put("/{id_usuario}", response_model=UsuarioResponse, dependencies=[Depends(require_admin)])
async def update_usuario(id_usuario: str, obj_in: UsuarioUpdate, db: AsyncSession = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        user_uuid = uuid.UUID(id_usuario)
    except ValueError:
        raise HTTPException(status_code=400, detail="UUID inválido")

    u = await usuario.get_by_id(db, id_usuario=user_uuid)
    if not u:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")
        
    valor_anterior = {k: getattr(u, k) for k in obj_in.model_dump(exclude_unset=True).keys()}
    
    updated_u = await usuario.update(db, db_obj=u, obj_in=obj_in)
    
    await log_audit_event(
        db=db,
        tipo_evento="UPDATE",
        entidad_afectada="usuario",
        pk_entidad=id_usuario,
        valor_anterior=valor_anterior,
        valor_nuevo=obj_in.model_dump(exclude_unset=True, mode='json'),
        id_usuario=current_user.get("sub"),
    )
    return updated_u

@router.put("/{id_usuario}/deactivate", response_model=UsuarioResponse, dependencies=[Depends(require_admin)])
async def deactivate_usuario(id_usuario: str, db: AsyncSession = Depends(get_db), current_user: dict = Depends(get_current_user)):
    try:
        user_uuid = uuid.UUID(id_usuario)
    except ValueError:
        raise HTTPException(status_code=400, detail="UUID inválido")

    u = await usuario.get_by_id(db, id_usuario=user_uuid)
    if not u:
        raise HTTPException(status_code=404, detail="Usuario no encontrado")
        
    if current_user.get("sub") == id_usuario:
        raise HTTPException(status_code=400, detail="No puede desactivar su propia cuenta")
        
    valor_anterior = {"estado_cuenta": getattr(u, "estado_cuenta")}
    
    updated_u = await usuario.update(db, db_obj=u, obj_in={"estado_cuenta": False})
    
    await log_audit_event(
        db=db,
        tipo_evento="USER_DEACTIVATED",
        entidad_afectada="usuario",
        pk_entidad=id_usuario,
        valor_anterior=valor_anterior,
        valor_nuevo={"estado_cuenta": False},
        id_usuario=current_user.get("sub"),
    )
    return updated_u
