/**
 * @file _data/mock.ts
 * @description Datos mock para el módulo de Búsqueda Global.
 * Reemplazar con datos reales del endpoint GET /api/v1/search cuando esté disponible.
 */

import type {
  SearchProject,
  SearchInvestigador,
  SearchPublicacion,
  SearchResult,
} from './types';

// ─────────────────────────────────────────────────────────────────────────────
// Proyectos (12 registros)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_PROJECTS: SearchProject[] = [
  {
    id:            'PRJ-26-045',
    codigo:        'PRJ-26-045',
    titulo:        'Análisis Predictivo basado en Inteligencia Artificial para Sistemas Distribuidos',
    tipo:          'Investigación Aplicada',
    convocatoria:  'VRIP 2026',
    estado:        'En Ejecución',
    resumen:       'La investigación tiene como objetivo desarrollar e implementar modelos de machine learning capaces de predecir cuellos de botella y fallos en cascada dentro de arquitecturas de microservicios de alta concurrencia. Se espera validar los resultados en un entorno de pruebas simulado utilizando logs de servidores universitarios.',
    monto:         45000,
    respaldoLegal: 'RR-08452-UNMSM',
    inicio:        '2026-06-01',
    fin:           '2027-06-01',
    responsable:   { nombre: 'Dra. Rosa Pérez', initials: 'RP' },
    grupo:         'IA en Salud Pública',
    fuente:        ['RAIS'],
    ultimaSync:    '10 May 2026, 06:15 AM',
    anio:          2026,
  },
  {
    id:            'PRJ-26-032',
    codigo:        'PRJ-26-032',
    titulo:        'Machine Learning para Diagnóstico Temprano de Enfermedades Cardíacas',
    tipo:          'Investigación Básica',
    convocatoria:  'VRIP 2026',
    estado:        'En Evaluación',
    resumen:       'Desarrollo de algoritmos de aprendizaje automático para la detección temprana de patologías cardíacas mediante el análisis de señales de electrocardiograma y datos clínicos de pacientes del HNERM.',
    monto:         38000,
    respaldoLegal: 'RR-07831-UNMSM',
    inicio:        '2026-08-01',
    fin:           '2027-08-01',
    responsable:   { nombre: 'Dr. Carlos Mendoza', initials: 'CM' },
    grupo:         'Bioinformática Clínica',
    fuente:        ['RAIS'],
    ultimaSync:    '09 May 2026, 10:00 AM',
    anio:          2026,
  },
  {
    id:            'PRJ-25-018',
    codigo:        'PRJ-25-018',
    titulo:        'Procesamiento de Lenguaje Natural para Análisis de Sentimientos en Redes Sociales',
    tipo:          'Investigación Aplicada',
    convocatoria:  'CONCYTEC 2025',
    estado:        'En Ejecución',
    resumen:       'Investigación orientada al análisis de opinión pública a través de redes sociales, utilizando modelos de transformers entrenados en corpus de español peruano.',
    monto:         52000,
    respaldoLegal: 'RR-06122-UNMSM',
    inicio:        '2025-03-01',
    fin:           '2026-03-01',
    responsable:   { nombre: 'Mg. Lucía Torres', initials: 'LT' },
    grupo:         'NLP y Minería de Datos',
    fuente:        ['RAIS'],
    ultimaSync:    '08 May 2026, 09:30 AM',
    anio:          2025,
  },
  {
    id:            'PRJ-24-007',
    codigo:        'PRJ-24-007',
    titulo:        'Visión Computacional para Control de Calidad en Industria Alimentaria',
    tipo:          'Investigación Aplicada',
    convocatoria:  'VRIP 2024',
    estado:        'Concluido',
    resumen:       'Sistema de inspección visual automatizado basado en redes neuronales convolucionales para la detección de defectos en productos alimenticios durante el proceso de empaque.',
    monto:         29500,
    respaldoLegal: 'RR-04821-UNMSM',
    inicio:        '2024-01-01',
    fin:           '2025-01-01',
    responsable:   { nombre: 'Dr. Pedro Quispe', initials: 'PQ' },
    grupo:         'Visión Artificial y Robótica',
    fuente:        ['RAIS'],
    ultimaSync:    '05 May 2026, 02:00 PM',
    anio:          2024,
  },
  {
    id:            'PRJ-26-060',
    codigo:        'PRJ-26-060',
    titulo:        'Sistemas de Recomendación Inteligente para Plataformas Educativas',
    tipo:          'Investigación Aplicada',
    convocatoria:  'VRIP 2026',
    estado:        'En Ejecución',
    resumen:       'Diseño e implementación de un motor de recomendación basado en filtrado colaborativo y contenido para personalizar el aprendizaje en plataformas e-learning universitarias.',
    monto:         41000,
    respaldoLegal: 'RR-09014-UNMSM',
    inicio:        '2026-07-01',
    fin:           '2027-07-01',
    responsable:   { nombre: 'Dra. Ana Vargas', initials: 'AV' },
    grupo:         'IA en Educación',
    fuente:        ['RAIS'],
    ultimaSync:    '10 May 2026, 07:00 AM',
    anio:          2026,
  },
  {
    id:            'PRJ-23-099',
    codigo:        'PRJ-23-099',
    titulo:        'Blockchain para Gestión de Identidad Digital en Sistemas Universitarios',
    tipo:          'Investigación Básica',
    convocatoria:  'CONCYTEC 2023',
    estado:        'Concluido',
    resumen:       'Exploración del uso de tecnología blockchain para garantizar la integridad y autenticación de identidades digitales en entornos académicos distribuidos.',
    monto:         35000,
    respaldoLegal: 'RR-03201-UNMSM',
    inicio:        '2023-06-01',
    fin:           '2024-06-01',
    responsable:   { nombre: 'Mg. Roberto Salas', initials: 'RS' },
    grupo:         'Seguridad Informática',
    fuente:        ['RAIS'],
    ultimaSync:    '01 May 2026, 11:00 AM',
    anio:          2023,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Investigadores (5 registros)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_INVESTIGADORES: SearchInvestigador[] = [
  {
    id:                  'INV-001',
    nombre:              'Dra. Rosa Pérez',
    cargo:               'Docente Principal a Dedicación Exclusiva',
    especialidad:        'Inteligencia Artificial y Ciencia de Datos',
    nivel:               'II',
    dni:                 '09384722',
    fuente:              ['RAIS', 'RENACYT'],
    grupo:               'IA en Salud Pública',
    ultimaSync:          'Hace 2 días',
    proyectosCount:      4,
    publicacionesCount:  18,
    email:               'rperez@unmsm.edu.pe',
    facultad:            'Facultad de Ingeniería de Sistemas e Informática',
    codigoRenacyt:       'P0039101',
  },
  {
    id:                  'INV-002',
    nombre:              'Dr. Carlos Mendoza',
    cargo:               'Docente Asociado a Tiempo Completo',
    especialidad:        'Bioinformática y Aprendizaje Automático',
    nivel:               'IV',
    dni:                 '07241893',
    fuente:              ['RAIS', 'RENACYT'],
    grupo:               'Bioinformática Clínica',
    ultimaSync:          'Hace 3 días',
    proyectosCount:      3,
    publicacionesCount:  12,
    email:               'cmendoza@unmsm.edu.pe',
    facultad:            'Facultad de Medicina',
    codigoRenacyt:       'P0186033',
  },
  {
    id:                  'INV-003',
    nombre:              'Mg. Lucía Torres',
    cargo:               'Docente Auxiliar',
    especialidad:        'Procesamiento de Lenguaje Natural',
    nivel:               'VI',
    dni:                 '44749497',
    fuente:              ['RAIS'],
    grupo:               'NLP y Minería de Datos',
    ultimaSync:          'Hace 1 semana',
    proyectosCount:      2,
    publicacionesCount:  7,
    email:               'ltorres@unmsm.edu.pe',
    facultad:            'Facultad de Ingeniería de Sistemas e Informática',
    codigoRenacyt:       'P0012345',
  },
  {
    id:                  'INV-004',
    nombre:              'Dr. Pedro Quispe',
    cargo:               'Docente Principal',
    especialidad:        'Visión Computacional y Robótica',
    nivel:               'III',
    dni:                 '10293847',
    fuente:              ['RAIS', 'RENACYT'],
    grupo:               'Visión Artificial y Robótica',
    ultimaSync:          'Hace 5 días',
    proyectosCount:      5,
    publicacionesCount:  22,
    email:               'pquispe@unmsm.edu.pe',
    facultad:            'Facultad de Ingeniería Industrial',
    codigoRenacyt:       'P0098712',
  },
  {
    id:                  'INV-005',
    nombre:              'Dra. Ana Vargas',
    cargo:               'Docente Asociada a Dedicación Exclusiva',
    especialidad:        'Tecnología Educativa e Inteligencia Artificial',
    nivel:               'V',
    dni:                 '28374655',
    fuente:              ['RENACYT'],
    grupo:               'IA en Educación',
    ultimaSync:          'Hace 1 día',
    proyectosCount:      3,
    publicacionesCount:  9,
    email:               'avargas@unmsm.edu.pe',
    facultad:            'Facultad de Educación',
    codigoRenacyt:       'P0231456',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Publicaciones (8 registros para demo)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_PUBLICACIONES: SearchPublicacion[] = [
  {
    id:        'PUB-2025-0112',
    titulo:    'Artificial Intelligence Applications in Rural Healthcare Systems',
    autores:   ['Pérez, R.', 'Doe, J.'],
    revista:   'Journal of Medical Systems (2025)',
    anio:      2025,
    doi:       '10.1016/j.health.2025.04',
    fuente:    'RAIS',
    quartil:   'Q1',
    ultimaAct: '15/04/2026',
    tipo:      'Artículo ISI',
    resumen:   'Este artículo presenta el diseño e implementación de sistemas de inteligencia artificial adaptados a entornos de salud rural en países en desarrollo, con énfasis en la optimización de recursos limitados y conectividad intermitente.',
  },
  {
    id:        'PUB-2025-0088',
    titulo:    'Deep Learning para el Diagnóstico de Retinopatía Diabética mediante Imágenes de Fondo de Ojo',
    autores:   ['Mendoza, C.', 'García, F.', 'López, M.'],
    revista:   'IEEE Transactions on Medical Imaging (2025)',
    anio:      2025,
    doi:       '10.1109/tmi.2025.1234567',
    fuente:    'RAIS',
    quartil:   'Q1',
    ultimaAct: '20/03/2026',
    tipo:      'Artículo ISI',
    resumen:   'Propuesta de una arquitectura CNN para la clasificación automática de grados de retinopatía diabética a partir de fotografías del fondo de ojo, con accuracy superior al 94% en el dataset MESSIDOR-2.',
  },
  {
    id:        'TES-2024-0031',
    titulo:    'Modelos de Lenguaje de Gran Escala para el Análisis Jurídico en el Contexto Latinoamericano',
    autores:   ['Torres, L.'],
    revista:   'UNMSM — Tesis Doctoral',
    anio:      2024,
    fuente:    'CyberTesis',
    ultimaAct: '10/12/2024',
    tipo:      'Tesis Doctoral',
    resumen:   'Exploración de modelos LLM fine-tuneados en corpus jurídico peruano para tareas de clasificación de jurisprudencia, extracción de entidades legales y generación de resúmenes de fallos judiciales.',
  },
  {
    id:        'PUB-2024-0201',
    titulo:    'Algoritmos Genéticos para la Optimización Multi-objetivo en Redes Logísticas',
    autores:   ['Quispe, P.', 'Rodríguez, A.'],
    revista:   'Expert Systems with Applications (2024)',
    anio:      2024,
    doi:       '10.1016/j.eswa.2024.112233',
    fuente:    'RAIS',
    quartil:   'Q2',
    ultimaAct: '05/01/2025',
    tipo:      'Artículo Scopus',
    resumen:   'Propuesta de un enfoque metaheurístico multi-objetivo para la optimización de rutas y asignación de recursos en redes de distribución logística con restricciones de tiempo.',
  },
  {
    id:        'PUB-2026-0044',
    titulo:    'Federated Learning para la Privacidad en Sistemas de Salud Distribuidos',
    autores:   ['Pérez, R.', 'Vargas, A.', 'Smith, J.'],
    revista:   'Nature Digital Medicine (2026)',
    anio:      2026,
    doi:       '10.1038/s41746-026-00312-x',
    fuente:    'RAIS',
    quartil:   'Q1',
    ultimaAct: '01/05/2026',
    tipo:      'Artículo ISI',
    resumen:   'Evaluación del aprendizaje federado como paradigma para entrenar modelos de IA en datos clínicos sin comprometer la privacidad del paciente, aplicado a redes de hospitales en el Perú.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Catálogos de apoyo
// ─────────────────────────────────────────────────────────────────────────────

export const GRUPOS_INVESTIGACION = [
  'IA en Salud Pública',
  'Bioinformática Clínica',
  'NLP y Minería de Datos',
  'Visión Artificial y Robótica',
  'IA en Educación',
  'Seguridad Informática',
];

// ─────────────────────────────────────────────────────────────────────────────
// Dataset unificado (para el servicio de búsqueda)
// ─────────────────────────────────────────────────────────────────────────────

export const ALL_RESULTS: SearchResult[] = [
  ...MOCK_PROJECTS.map((data) => ({ type: 'proyecto' as const, data })),
  ...MOCK_INVESTIGADORES.map((data) => ({ type: 'investigador' as const, data })),
  ...MOCK_PUBLICACIONES.map((data) => ({ type: 'publicacion' as const, data })),
];
